import bpy

from .load_mc_textures import MC_TEXTURES_LOAD_OT_SET, MC_TEXTURES_IMPORT_OT_SET, MC_TEXTURES_SKIP_OT_SET
from .append_misc import THOMAS_RIG_LEGACY_APPEND_MISC
from .append_rig_base import THOMAS_RIG_LEGACY_APPEND_CAPE, THOMAS_RIG_LEGACY_APPEND_ELYTRA
from .armor_tab_set import THOMAS_RIG_ASSETS_ARMOR_TAB_OT_SET
from .armor import THOMAS_RIG_ARMOR_ADD
from .img_pack_reload import THOMAS_RIG_IMG_PACK, THOMAS_RIG_IMAGERELOAD
from .remove_rig_base import THOMAS_RIG_LEGACY_REMOVE_CAPE, THOMAS_RIG_LEGACY_REMOVE_ELYTRA
from .skin_download import THOMAS_RIG_SKIN_DOWNLOAD
from .tool_parent import THOMAS_RIG_TOOL_PARENT
from .rig_update import THOMAS_RIG_UPDATE_RIG


classes = (
    MC_TEXTURES_IMPORT_OT_SET,
    MC_TEXTURES_SKIP_OT_SET,
    MC_TEXTURES_LOAD_OT_SET,
    THOMAS_RIG_SKIN_DOWNLOAD,
    THOMAS_RIG_ASSETS_ARMOR_TAB_OT_SET,
    THOMAS_RIG_ARMOR_ADD,
    THOMAS_RIG_TOOL_PARENT,
    THOMAS_RIG_LEGACY_APPEND_CAPE,
    THOMAS_RIG_LEGACY_REMOVE_CAPE,
    THOMAS_RIG_LEGACY_APPEND_ELYTRA,
    THOMAS_RIG_LEGACY_REMOVE_ELYTRA,
    THOMAS_RIG_LEGACY_APPEND_MISC,
    THOMAS_RIG_IMG_PACK,
    THOMAS_RIG_IMAGERELOAD,
    THOMAS_RIG_UPDATE_RIG,
)

register, unregister = bpy.utils.register_classes_factory(classes)